server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # React Router (SPA) — noma'lum yo'llar index.html'ga qaytariladi
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
